name          'puppet-zookeeper'
version       '0.0.1'
source        'UNKNOWN'
author        'puppet'
license       'Apache License, Version 2.0'
summary       'This module installs and manages zookeeper'
description   'UNKNOWN'
project_page  'UNKNOWN'
dependency    'puppetlabs/stdlib'
