name          'puppet-zookeeper'
version       '0.0.1'
source        'UNKNOWN'
author        'Hingst, Arne-Kristian'
license       'Apache License, Version 2.0'
summary       'This module installs and manages zookeeper'
description   'ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.'
project_page  'https://github.com/hingstarne/puppet-zookeeper'
dependency    'puppetlabs/stdlib'
dependency    'puppetlabs/apt'
